id: I86051FD2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:12:29+00:00'
last_modified: '2022-06-10T11:18:13.440168+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22096
  title: གསུང་འབུམ། འགྱུར་མེད་རྡོ་རྗེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E284:
      image_group_id: I2195
      title: ''
      total_pages: 726
      order: 1
      base_file: E284.txt
    B9FF:
      image_group_id: I2196
      title: ''
      total_pages: 644
      order: 2
      base_file: B9FF.txt
    '9934':
      image_group_id: I2197
      title: ''
      total_pages: 668
      order: 3
      base_file: 9934.txt
    '7968':
      image_group_id: I2198
      title: ''
      total_pages: 614
      order: 4
      base_file: 7968.txt
    FC22:
      image_group_id: I2199
      title: ''
      total_pages: 634
      order: 5
      base_file: FC22.txt
    FDA8:
      image_group_id: I2200
      title: ''
      total_pages: 690
      order: 6
      base_file: FDA8.txt
    F446:
      image_group_id: I2201
      title: ''
      total_pages: 772
      order: 7
      base_file: F446.txt
    9D7B:
      image_group_id: I2202
      title: ''
      total_pages: 730
      order: 8
      base_file: 9D7B.txt
    580F:
      image_group_id: I2203
      title: ''
      total_pages: 782
      order: 9
      base_file: 580F.txt
    4ECF:
      image_group_id: I2204
      title: ''
      total_pages: 724
      order: 10
      base_file: 4ECF.txt
    1D61:
      image_group_id: I2205
      title: ''
      total_pages: 746
      order: 11
      base_file: 1D61.txt
    4ABB:
      image_group_id: I2206
      title: ''
      total_pages: 674
      order: 12
      base_file: 4ABB.txt
    6C61:
      image_group_id: I2207
      title: ''
      total_pages: 784
      order: 13
      base_file: 6C61.txt
    C03C:
      image_group_id: I2208
      title: ''
      total_pages: 666
      order: 14
      base_file: C03C.txt
    '5513':
      image_group_id: I2209
      title: ''
      total_pages: 602
      order: 15
      base_file: 5513.txt
    D9A7:
      image_group_id: I2210
      title: ''
      total_pages: 766
      order: 16
      base_file: D9A7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
