id: P008008
initial_creation_type: ocr
source_metadata:
  id: bdr:W22096
  title: གསུང་འབུམ། འགྱུར་མེད་རྡོ་རྗེ
  author: ''
  volumes:
    a7d382561bea4f14b46ac3d768ecf527:
      image_group_id: I2195
      title: ''
      volume_number: 1
      total_pages: 726
    c9a9828393e0460791a90aed79f60bb1:
      image_group_id: I2196
      title: ''
      volume_number: 2
      total_pages: 644
    b1341e3ffa784c03bd59a0818dd961fe:
      image_group_id: I2197
      title: ''
      volume_number: 3
      total_pages: 668
    7421884246ca46d08b652db1ac32bf94:
      image_group_id: I2198
      title: ''
      volume_number: 4
      total_pages: 614
    7c9ba46a6dbb4a66a12767196aba7181:
      image_group_id: I2199
      title: ''
      volume_number: 5
      total_pages: 634
    05aa2ae2f04b4f38aa37e6e10c9b687f:
      image_group_id: I2200
      title: ''
      volume_number: 6
      total_pages: 690
    46e1ae38eb374010980726a1fa6a8f31:
      image_group_id: I2201
      title: ''
      volume_number: 7
      total_pages: 772
    7ca5a891a44343fea0dbf683a039c67d:
      image_group_id: I2202
      title: ''
      volume_number: 8
      total_pages: 730
    a6eca1b69c314a0fab0d1cf7ee6b0633:
      image_group_id: I2203
      title: ''
      volume_number: 9
      total_pages: 782
    460ec6d3a9a947f49262b0996acac64d:
      image_group_id: I2204
      title: ''
      volume_number: 10
      total_pages: 724
    4dd649691a7a40bf82dcaab4ae05d073:
      image_group_id: I2205
      title: ''
      volume_number: 11
      total_pages: 746
    b24a09003b184f81b61e8c530de189f7:
      image_group_id: I2206
      title: ''
      volume_number: 12
      total_pages: 674
    8a474b0a5ffc4725947db5c634ef593e:
      image_group_id: I2207
      title: ''
      volume_number: 13
      total_pages: 784
    bbaa1476f9ba4567a019a131e2be4645:
      image_group_id: I2208
      title: ''
      volume_number: 14
      total_pages: 666
    50b94e4c2eaa41a89e5aedf2d3364179:
      image_group_id: I2209
      title: ''
      volume_number: 15
      total_pages: 602
    d8d5fe45249449ceb360e6d2ff5ec7fd:
      image_group_id: I2210
      title: ''
      volume_number: 16
      total_pages: 766
ebook_metadata:
  title: གསུང་འབུམ། འགྱུར་མེད་རྡོ་རྗེ
  author: ''
  sku: P008008
  cover: cover.jpg
  layers:
  - pagination
