id: opecha:P008008
initial_creation_type: ocr
source_metadata:
  id: bdr:W22096
  title: གསུང་འབུམ། འགྱུར་མེད་རྡོ་རྗེ
  volume:
    ccb6127f798d4df8bd1c3cda64fd756d:
      image_group_id: I2195
      title: ''
      volume_number: 1
      total_pages: 726
    c1311982f722406a9c1b17608972a1f8:
      image_group_id: I2196
      title: ''
      volume_number: 2
      total_pages: 644
    9827d0ca8c454a58871ba4dbd1274ccd:
      image_group_id: I2197
      title: ''
      volume_number: 3
      total_pages: 668
    8d233e9a030f435fb11bfbb0d5b753a6:
      image_group_id: I2198
      title: ''
      volume_number: 4
      total_pages: 614
    06421956fcbf4f25bea87362438c7c21:
      image_group_id: I2199
      title: ''
      volume_number: 5
      total_pages: 634
    473f91e9e82141949dafaa2421a8761d:
      image_group_id: I2200
      title: ''
      volume_number: 6
      total_pages: 690
    365b132d120d448cbf56e59feb8639b7:
      image_group_id: I2201
      title: ''
      volume_number: 7
      total_pages: 772
    4252c41896764131ad7f6eda516bcdaa:
      image_group_id: I2202
      title: ''
      volume_number: 8
      total_pages: 730
    9215f849eb1d43869501dcc63cd8f158:
      image_group_id: I2203
      title: ''
      volume_number: 9
      total_pages: 782
    7b99aa90224d4cdb94b4e4481de56a2c:
      image_group_id: I2204
      title: ''
      volume_number: 10
      total_pages: 724
    a0fe4d73cf16477c840d9dac76000ff2:
      image_group_id: I2205
      title: ''
      volume_number: 11
      total_pages: 746
    c1536cb2f5404b4eb357ed66939970f0:
      image_group_id: I2206
      title: ''
      volume_number: 12
      total_pages: 674
    9f0407f3bd384c15a92cf461c00b9c24:
      image_group_id: I2207
      title: ''
      volume_number: 13
      total_pages: 784
    da379e5f8f294be48ea9b1c4e981a755:
      image_group_id: I2208
      title: ''
      volume_number: 14
      total_pages: 666
    7fe3055554874579b30593aad22e5700:
      image_group_id: I2209
      title: ''
      volume_number: 15
      total_pages: 602
    73d28b44182441e1b4a113cc9c75922c:
      image_group_id: I2210
      title: ''
      volume_number: 16
      total_pages: 766
  author: ''
ebook_metadata:
  title: གསུང་འབུམ། འགྱུར་མེད་རྡོ་རྗེ
  author: ''
  sku: P008008
  cover: cover.jpg
  layers:
  - pagination
